set(CACHE{PLASMA_IONS_CHINA_QWEATHER_PRIVATE_KEY} TYPE FILEPATH
    HELP "The path to the private key to sign qweather jwt token."
    VALUE "")
set(CACHE{PLASMA_IONS_CHINA_QWEATHER_KID} TYPE STRING
    HELP "The kid of qweather jwt token header."
    VALUE "")
set(CACHE{PLASMA_IONS_CHINA_QWEATHER_SUB} TYPE STRING
    HELP "The sub of qweather jwt token payload."
    VALUE "")
set(CACHE{PLASMA_IONS_CHINA_QWEATHER_API_HOST} TYPE STRING
    HELP "The api host of qweather api request."
    VALUE "")
if (NOT IS_READABLE "${PLASMA_IONS_CHINA_QWEATHER_PRIVATE_KEY}")
    message(WARNING
          "qweather: Private key is not readable, skip adding QWeather ion.")
    return()
endif()
if (NOT PLASMA_IONS_CHINA_QWEATHER_KID)
    message(WARNING "qweather: KID is empty, skip adding QWeather ion.")
    return()
endif()
if (NOT PLASMA_IONS_CHINA_QWEATHER_SUB)
    message(WARNING "qweather: SUB is empty, skip adding QWeather ion.")
    return()
endif()
if (NOT PLASMA_IONS_CHINA_QWEATHER_API_HOST)
    message(WARNING "qweather: API_HOST is empty, skip adding QWeather ion.")
    return()
endif()

function(plasma_ions_china_declare_qweather_credential)
    set(options)
    set(oneValueArgs PRIVATE_KEY KID SUB API_HOST HEADER)
    set(multiValuesArgs)

    cmake_parse_arguments(PARSE_ARGV 1 PLASMA_IONS_CHINA
                          "${options}"
                          "${oneValueArgs}"
                          "${multiValuesArgs}")
    set(PLASMA_IONS_CHINA_TARGET ${ARGV0})
    cmake_path(ABSOLUTE_PATH PLASMA_IONS_CHINA_PRIVATE_KEY
                BASE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
                OUTPUT_VARIABLE PLASMA_IONS_CHINA_PRIVATE_KEY_ABSOLUTE)
    cmake_path(ABSOLUTE_PATH PLASMA_IONS_CHINA_HEADER
                BASE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}"
                OUTPUT_VARIABLE PLASMA_IONS_CHINA_HEADER_ABSOLUTE)
    cmake_path(GET PLASMA_IONS_CHINA_HEADER_ABSOLUTE PARENT_PATH
                PLASMA_IONS_CHINA_HEADER_INCLUDE_DIR)
    get_target_property(
        PLASMA_IONS_CHINA_${PLASMA_IONS_CHINA_TARGET}_INCLUDE_DIR
        ${PLASMA_IONS_CHINA_TARGET}
        INCLUDE_DIRECTORIES)
    if(NOT PLASMA_IONS_CHINA_HEADER_INCLUDE_DIR IN_LIST
        PLASMA_IONS_CHINA_${PLASMA_IONS_CHINA_TARGET}_INCLUDE_DIR)
        target_include_directories(${PLASMA_IONS_CHINA_TARGET}
            PRIVATE "${PLASMA_IONS_CHINA_HEADER_INCLUDE_DIR}")
    endif()
    file(CONFIGURE
        OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/generate-qweather-credential.py"
        CONTENT [=[
from pathlib import Path
from base64 import b64decode

PRIVATE_KEY = Path("@PLASMA_IONS_CHINA_PRIVATE_KEY_ABSOLUTE@")
HEADER = Path("@PLASMA_IONS_CHINA_HEADER_ABSOLUTE@")

lines = [
    "// This file was generated by plasma_ions_china_declare_qweather_credential(): DO NOT EDIT!",
    "",
    "#pragma once",
    "",
    "#define KID \"@PLASMA_IONS_CHINA_KID@\"",
    "#define SUB \"@PLASMA_IONS_CHINA_SUB@\"",
    "#define API_HOST \"@PLASMA_IONS_CHINA_API_HOST@\"",
]
private_key_lines = PRIVATE_KEY.read_text().splitlines()
start = private_key_lines.index("-----BEGIN PRIVATE KEY-----")
assert start >= 0
end = private_key_lines.index("-----END PRIVATE KEY-----", start)
assert end > start
seed = b64decode("".join(private_key_lines[start+1:end]))[-32:]
lines.append("const unsigned char PRIVATE_KEY_SEED[] = {")
lines.append(", ".join([f"0x{b:02x}" for b in seed]))
lines.append("};")

HEADER.parent.mkdir(parents = True, exist_ok = True)
HEADER.write_text("\n".join(lines))
        ]=]
        @ONLY)
    find_package(Python 3.4 REQUIRED)
    add_custom_command(OUTPUT "${PLASMA_IONS_CHINA_HEADER_ABSOLUTE}"
        COMMAND Python::Interpreter "${CMAKE_CURRENT_BINARY_DIR}/generate-qweather-credential.py"
        DEPENDS "${PLASMA_IONS_CHINA_PRIVATE_KEY_ABSOLUTE}"
        COMMENT "Generating QWeather credential header..."
        VERBATIM)
    add_custom_target(${PLASMA_IONS_CHINA_TARGET}-credential
        DEPENDS "${PLASMA_IONS_CHINA_HEADER_ABSOLUTE}")
    add_dependencies(${PLASMA_IONS_CHINA_TARGET} ${PLASMA_IONS_CHINA_TARGET}-credential)
endfunction()

kcoreaddons_add_plugin(qweather INSTALL_NAMESPACE "${ION_INSTALL_NAMESPACE}")
target_sources(qweather PRIVATE qweather.hpp qweather.cpp)
ecm_qt_declare_logging_category(qweather
                                HEADER qweather_debug.hpp
                                IDENTIFIER WEATHER::ION::QWEATHER
                                CATEGORY_NAME org.kde.weather.ion.qweather
                                DEFAULT_SEVERITY Info
                                DESCRIPTION "www.qweather.com ion plugin"
                                EXPORT PLASMAWORKSPACE)

plasma_ions_china_declare_qweather_credential(qweather
    PRIVATE_KEY "${PLASMA_IONS_CHINA_QWEATHER_PRIVATE_KEY}"
    KID "${PLASMA_IONS_CHINA_QWEATHER_KID}"
    SUB "${PLASMA_IONS_CHINA_QWEATHER_SUB}"
    API_HOST "${PLASMA_IONS_CHINA_QWEATHER_API_HOST}"
    HEADER qweather_credential.hpp)

find_package(Qt${QT_MAJOR_VERSION} ${QT_MIN_VERSION} REQUIRED
             COMPONENTS Core Network)
cmake_pkg_config(IMPORT libsodium >=1.0.0 REQUIRED)
target_link_libraries(qweather PRIVATE
                      Plasma::Weather::Ion
                      PkgConfig::libsodium
                      Qt::Core
                      Qt::Network
                      KF${KF_MAJOR_VERSION}::UnitConversion
                      KF${KF_MAJOR_VERSION}::I18n
                      KF${KF_MAJOR_VERSION}::CoreAddons)
